	-- Changes for combat tactics overhaul

	NDefines.NMilitary.ATTACK_TO_DAMAGE_MULT = 0.03					-- Attack value of troops is multiplied by this when doing damage
 	NDefines.NMilitary.MORALELOSS_FACTOR = 1.5						-- Affects the morale loss rate in combats (higher gives bigger losses)

	NDefines.NMilitary.LIGHT_INFANTRY_MORALE = 2
	NDefines.NMilitary.LIGHT_INFANTRY_MAINTENANCE = 0.70
	NDefines.NMilitary.LIGHT_INFANTRY_PHASE_SKIRMISH_ATTACK = 1.25
	NDefines.NMilitary.LIGHT_INFANTRY_PHASE_SKIRMISH_DEFENSE = 2
	NDefines.NMilitary.LIGHT_INFANTRY_PHASE_MELEE_ATTACK = 1
	NDefines.NMilitary.LIGHT_INFANTRY_PHASE_MELEE_DEFENSE = 1
	NDefines.NMilitary.LIGHT_INFANTRY_PHASE_PURSUE_ATTACK = 2
	NDefines.NMilitary.LIGHT_INFANTRY_PHASE_PURSUE_DEFENSE = 2.5

	NDefines.NMilitary.HEAVY_INFANTRY_MORALE = 4
	NDefines.NMilitary.HEAVY_INFANTRY_MAINTENANCE = 3
	NDefines.NMilitary.HEAVY_INFANTRY_PHASE_SKIRMISH_ATTACK = 0.25
	NDefines.NMilitary.HEAVY_INFANTRY_PHASE_SKIRMISH_DEFENSE = 3
	NDefines.NMilitary.HEAVY_INFANTRY_PHASE_MELEE_ATTACK = 6
	NDefines.NMilitary.HEAVY_INFANTRY_PHASE_MELEE_DEFENSE = 4
	NDefines.NMilitary.HEAVY_INFANTRY_PHASE_PURSUE_ATTACK = 1
	NDefines.NMilitary.HEAVY_INFANTRY_PHASE_PURSUE_DEFENSE = 4

	NDefines.NMilitary.PIKEMEN_MORALE = 6
	NDefines.NMilitary.PIKEMEN_MAINTENANCE = 2.5
	NDefines.NMilitary.PIKEMEN_PHASE_SKIRMISH_ATTACK = 0.1
	NDefines.NMilitary.PIKEMEN_PHASE_SKIRMISH_DEFENSE = 4
	NDefines.NMilitary.PIKEMEN_PHASE_MELEE_ATTACK = 4.5
	NDefines.NMilitary.PIKEMEN_PHASE_MELEE_DEFENSE = 4.5
	NDefines.NMilitary.PIKEMEN_PHASE_PURSUE_ATTACK = 0.2
	NDefines.NMilitary.PIKEMEN_PHASE_PURSUE_DEFENSE = 2

	NDefines.NMilitary.LIGHT_CAVALRY_MORALE = 4
	NDefines.NMilitary.LIGHT_CAVALRY_MAINTENANCE = 3
	NDefines.NMilitary.LIGHT_CAVALRY_PHASE_SKIRMISH_ATTACK = 2
	NDefines.NMilitary.LIGHT_CAVALRY_PHASE_SKIRMISH_DEFENSE = 4.5
	NDefines.NMilitary.LIGHT_CAVALRY_PHASE_MELEE_ATTACK = 3
	NDefines.NMilitary.LIGHT_CAVALRY_PHASE_MELEE_DEFENSE = 3
	NDefines.NMilitary.LIGHT_CAVALRY_PHASE_PURSUE_ATTACK = 6
	NDefines.NMilitary.LIGHT_CAVALRY_PHASE_PURSUE_DEFENSE = 4.5

	NDefines.NMilitary.KNIGHTS_MORALE = 10
	NDefines.NMilitary.KNIGHTS_MAINTENANCE = 6
	NDefines.NMilitary.KNIGHTS_PHASE_SKIRMISH_ATTACK = 0.5
	NDefines.NMilitary.KNIGHTS_PHASE_SKIRMISH_DEFENSE = 6
	NDefines.NMilitary.KNIGHTS_PHASE_MELEE_ATTACK = 10
	NDefines.NMilitary.KNIGHTS_PHASE_MELEE_DEFENSE = 6
	NDefines.NMilitary.KNIGHTS_PHASE_PURSUE_ATTACK = 4
	NDefines.NMilitary.KNIGHTS_PHASE_PURSUE_DEFENSE = 5

	NDefines.NMilitary.ARCHERS_MORALE = 1
	NDefines.NMilitary.ARCHERS_MAINTENANCE = 2
	NDefines.NMilitary.ARCHERS_PHASE_SKIRMISH_ATTACK = 2
	NDefines.NMilitary.ARCHERS_PHASE_SKIRMISH_DEFENSE = 1.5
	NDefines.NMilitary.ARCHERS_PHASE_MELEE_ATTACK = 1
	NDefines.NMilitary.ARCHERS_PHASE_MELEE_DEFENSE = 1.5
	NDefines.NMilitary.ARCHERS_PHASE_PURSUE_ATTACK = 2
	NDefines.NMilitary.ARCHERS_PHASE_PURSUE_DEFENSE = 2.25